name: CI Frontend

on:
  push:
    branches: [ main ]
    paths:
      - 'client/**'
      - '.github/workflows/ci-frontend.yml'
  workflow_dispatch:

env:
  IMAGE_TAG: ${{ github.sha }}
  GHCR: ghcr.io/${{ github.repository_owner }}
  REPO_NAME: ${{ github.event.repository.name }}
  HELM_REPO: phanminhtri667/kltn_HR_managementkltn_helm


permissions:
  contents: write
  packages: write

jobs:
  build-and-push-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PASS_TOKEN }}

      - name: Build + Push frontend
        run: |
          SAFE_REPO=$(echo "$REPO_NAME" | tr '[:upper:]' '[:lower:]' | tr '_' '-')
          IMAGE_NAME="$GHCR/$SAFE_REPO-frontend:${IMAGE_TAG}"
          docker build --build-arg REACT_APP_API_URL=http://34.170.254.33:8080/api \
            -t "$IMAGE_NAME" ./client
          docker push "$IMAGE_NAME"

  update-helm-frontend:
    needs: build-and-push-frontend
    runs-on: ubuntu-latest

    steps:
      - name: Clone Helm Repo (private, via PAT)
        run: |
          git clone https://x-access-token:${{ secrets.PASS_TOKEN }}@github.com/${{ env.HELM_REPO }}.git helm

      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq

      - name: Update image tag
        working-directory: helm/kltn
        run: |
          yq -i ".frontend.image.tag = \"${IMAGE_TAG}\"" values.yaml

      - name: Commit & push
        working-directory: helm
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add kltn/values.yaml
          git commit -m "Update frontend tag to ${IMAGE_TAG}" || echo "No changes"
          git push https://x-access-token:${{ secrets.PASS_TOKEN }}@github.com/${{ env.HELM_REPO }}.git HEAD:main
